Revert "netfilter: x_tables: check for size overflow"
This reverts commit 3fa4744338fd4af994cd169e0429534172018923.

Broken build. Fixing build error:
x_tables.c:664:19: error: 'info' undeclared (first use in this function)

Change-Id: I74dc059e5db67acbe058c88edb84d301a4e25f09