Update patch set 1
Patch Set 1:

> > Patch Set 1:
 > >
 > > Moshe's rebase fails to build on x2.
 > >
 > > Marc Bourgoin:
 > > drivers/built-in.o: In function `msm_pc_debug_counters_phys':
 > > drv2604l.c:(.data+0x85208): undefined reference to
 > `lm3643_flash_led_init'
 > > drv2604l.c:(.data+0x85210): undefined reference to
 > `lm3643_flash_led_release'
 > > drv2604l.c:(.data+0x85218): undefined reference to
 > `lm3643_flash_led_off'
 > > drv2604l.c:(.data+0x85220): undefined reference to
 > `lm3643_flash_led_low'
 > > drv2604l.c:(.data+0x85228): undefined reference to
 > `lm3643_flash_led_high'
 > > drv2604l.c:(.data+0x85238): undefined reference to
 > `lm3643_flash_led_init'
 > > drv2604l.c:(.data+0x85240): undefined reference to
 > `lm3643_flash_led_release'
 > > drv2604l.c:(.data+0x85248): undefined reference to
 > `lm3643_flash_led_off'
 > > drv2604l.c:(.data+0x85250): undefined reference to
 > `lm3643_flash_led_low'
 > > drv2604l.c:(.data+0x85258): undefined reference to
 > `lm3643_flash_led_high'
 > 
 > Which brings me back to question the whole upstreaming again.
 > What's the problem with a working CAF tag? IMHO upstreaming causes
 > a lot of trouble just for the sake of a higher patch level.

This problem, is not caused from upstreaming. It is caused by a custom patch, imho, that Moshe did. I'll check it for X2 and report back. As long as CAF...in Oreo, there is no problem in upstreaming a kernel.

Patch-set: 1
Reviewer: Stergios P. <8846@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=0